# Generated by Django 5.2.6 on 2025-10-30 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_empresa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='rut',
            new_name='codigo',
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefono',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
